/** @format */

import type { CommandPaletteItem } from "@/components/commandPalette/types";
import {
	GridSquare,
	Users,
	InvoiceDollar,
	ClipboardText,
	ChatText,
	Gear,
	ChartSquare,
	HeadphoneSimple,
	FolderOpen,
} from "@/Icons";

export const navigationActions: CommandPaletteItem[] = [
	{
		id: "nav-dashboard",
		type: "navigation",
		label: "nav.dashboard",
		icon: GridSquare,
		category: "all",
		path: "/dashboard",
	},
	{
		id: "nav-members",
		type: "navigation",
		label: "nav.members",
		description: "commandPalette.descriptions.viewTeamMembers",
		icon: Users,
		category: "members",
		path: "/dashboard/members",
	},
	{
		id: "nav-contracts",
		type: "navigation",
		label: "nav.contracts",
		description: "commandPalette.descriptions.manageContracts",
		icon: ClipboardText,
		category: "contracts",
		path: "/dashboard/contracts",
	},
	{
		id: "nav-requests",
		type: "navigation",
		label: "nav.requests",
		description: "commandPalette.descriptions.viewRequests",
		icon: ClipboardText,
		category: "all",
		path: "/dashboard/requests",
		shortcut: "R",
	},
	{
		id: "nav-vouchers",
		type: "navigation",
		label: "nav.vouchers",
		description: "commandPalette.descriptions.paymentReceiptVouchers",
		icon: InvoiceDollar,
		category: "vouchers",
		path: "/dashboard/vouchers",
	},
	{
		id: "nav-legal-cases",
		type: "navigation",
		label: "nav.legalCases",
		description: "commandPalette.descriptions.manageLegalCases",
		icon: FolderOpen,
		category: "legalCases",
		path: "/dashboard/legal-cases",
	},
	{
		id: "nav-loans-advances",
		type: "navigation",
		label: "nav.loansAdvances",
		description: "commandPalette.descriptions.employeeLoans",
		icon: InvoiceDollar,
		category: "all",
		path: "/dashboard/loans-advances",
	},
	{
		id: "nav-messages",
		type: "navigation",
		label: "nav.communication",
		description: "commandPalette.descriptions.teamCommunication",
		icon: ChatText,
		category: "all",
		path: "/dashboard/messages",
		shortcut: "M",
	},
	{
		id: "nav-reports",
		type: "navigation",
		label: "nav.reports",
		description: "commandPalette.descriptions.viewReports",
		icon: ChartSquare,
		category: "all",
		path: "/dashboard/reports",
	},
	{
		id: "nav-help-support",
		type: "navigation",
		label: "nav.helpSupport",
		description: "commandPalette.descriptions.helpSupport",
		icon: HeadphoneSimple,
		category: "all",
		path: "/dashboard/help-support",
	},
	{
		id: "nav-settings",
		type: "navigation",
		label: "commandPalette.actions.settings",
		description: "commandPalette.descriptions.appSettings",
		icon: Gear,
		category: "settings",
		path: "/settings/general",
	},
	{
		id: "nav-settings-general",
		type: "navigation",
		label: "commandPalette.actions.generalSettings",
		description: "commandPalette.descriptions.generalSettings",
		icon: Gear,
		category: "settings",
		path: "/settings/general",
	},
	{
		id: "nav-settings-people-access",
		type: "navigation",
		label: "commandPalette.actions.peopleAccess",
		description: "commandPalette.descriptions.managePermissions",
		icon: Gear,
		category: "settings",
		path: "/settings/people-access",
	},
	{
		id: "nav-settings-company",
		type: "navigation",
		label: "commandPalette.actions.companySettings",
		description: "commandPalette.descriptions.companyDetails",
		icon: Gear,
		category: "settings",
		path: "/settings/company",
	},
	{
		id: "nav-settings-assets",
		type: "navigation",
		label: "commandPalette.actions.assets",
		description: "commandPalette.descriptions.manageAssets",
		icon: Gear,
		category: "settings",
		path: "/settings/assets",
	},
	{
		id: "nav-settings-service-catalog",
		type: "navigation",
		label: "commandPalette.actions.serviceCatalog",
		description: "commandPalette.descriptions.manageServices",
		icon: Gear,
		category: "settings",
		path: "/settings/service-catalog",
	},
	{
		id: "nav-settings-invoice-profiles",
		type: "navigation",
		label: "commandPalette.actions.invoiceProfiles",
		description: "commandPalette.descriptions.manageInvoiceProfiles",
		icon: Gear,
		category: "settings",
		path: "/settings/invoice-profiles",
	},
	{
		id: "nav-settings-voucher-types",
		type: "navigation",
		label: "commandPalette.actions.voucherTypes",
		description: "commandPalette.descriptions.manageVoucherTypes",
		icon: Gear,
		category: "settings",
		path: "/settings/voucher-types",
	},
	{
		id: "nav-settings-expense-types",
		type: "navigation",
		label: "commandPalette.actions.expenseTypes",
		description: "commandPalette.descriptions.manageExpenseTypes",
		icon: Gear,
		category: "settings",
		path: "/settings/expense-types",
	},
	{
		id: "nav-settings-income-types",
		type: "navigation",
		label: "commandPalette.actions.incomeTypes",
		description: "commandPalette.descriptions.manageIncomeTypes",
		icon: Gear,
		category: "settings",
		path: "/settings/income-types",
	},
	{
		id: "nav-settings-pretty-cash-names",
		type: "navigation",
		label: "commandPalette.actions.prettyCashNames",
		description: "commandPalette.descriptions.managePrettyCash",
		icon: Gear,
		category: "settings",
		path: "/settings/pretty-cash-names",
	},
	{
		id: "nav-settings-banks",
		type: "navigation",
		label: "commandPalette.actions.banks",
		description: "commandPalette.descriptions.manageBanks",
		icon: Gear,
		category: "settings",
		path: "/settings/banks",
	},
];
